name: Enhancement Tracking Issue
description: Provide supporting details for a feature in development
labels: kind/feature
body:
  - type: markdown
    attributes:
      value: "## Thank you for contributing to our Kompose!"
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Describe what feature/enhancement that you want to be added to Kompose.
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why is this needed?
    validations:
      required: true
