#!/bin/bash
set -e

source "$(dirname "$BASH_SOURCE")/.build"

if [ -z "$1" ]; then
    OS_PLATFORM_ARG=(-os="darwin linux windows")
else
    OS_PLATFORM_ARG=($1)
fi

if [ -z "$2" ]; then
    OS_ARCH_ARG=(-arch="386 amd64")
else
    OS_ARCH_ARG=($2)
fi

GITCOMMIT=$(git rev-parse --short HEAD)

# Get rid of existing binaries
rm -f kompose*

# Build binaries
gox "${OS_PLATFORM_ARG[@]}" "${OS_ARCH_ARG[@]}" \
    -output="bundles/kompose_{{.OS}}-{{.Arch}}/kompose" \
    "${BUILD_FLAGS[@]}" \
    .
