#!/bin/bash

# Copyright 2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

source "$(dirname "$BASH_SOURCE")/.build"

OUT_FILE="./kompose"

# Get rid of existing binary
rm -f $OUT_FILE

# Build binary
go build \
    "${BUILD_FLAGS[@]}" \
    -o $OUT_FILE \
    main.go

if [ $? -eq 0 ]; then
  echo "Build successful. Program saved as ${OUT_FILE}"
else
  echo "Build failed."
fi
