#!/bin/bash
set -e

source "$(dirname "$BASH_SOURCE")/.build"

OUT_FILE="./kompose"

# Get rid of existing binary
rm -f $OUT_FILE

# Build binary
go build \
    "${BUILD_FLAGS[@]}" \
    -o $OUT_FILE \
    ./cli/main

if [ $? -eq 0 ]; then
  echo "Build successful. Program saved as ${OUT_FILE}"
else
  echo "Build failed."
fi
