#!/usr/bin/env bash

# Copyright 2016 The Kubernetes Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "$(dirname "$BASH_SOURCE")/.validate"

# folders=$(find * -type d | egrep -v '^Godeps|bundles|.git')

IFS=$'\n'
files=( $(validate_diff --diff-filter=ACMR --name-only -- '*' | grep -v '^vendor/' || true) )
unset IFS

badFiles=()
for f in "${files[@]}"; do
    if [ $(grep -r "^<<<<<<<" $f) ]; then
        badFiles+=( "$f" )
        continue
    fi

    if [ $(grep -r "^>>>>>>>" $f) ]; then
        badFiles+=( "$f" )
        continue
    fi

    if [ $(grep -r "^=======$" $f) ]; then
        badFiles+=( "$f" )
        continue
    fi
    set -e
done


if [ ${#badFiles[@]} -eq 0 ]; then
	echo 'Congratulations!  There is no conflict.'
else
	{
		echo "There is trace of conflict(s) in the following files :"
		for f in "${badFiles[@]}"; do
			echo " - $f"
		done
		echo
		echo 'Please fix the conflict(s) commit the result.'
		echo
	} >&2
	false
fi
