name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Avoid noisy outputs like "tput: No value for $TERM and no -T specified"
  TERM: dumb

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

    - name: Build
      run: make bin

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: "kompose"
        path: "kompose"
