name: Unit and Integration tests
on:
  push:
    branches:
      - master
  pull_request:
env:
  # Avoid noisy outputs like "tput: No value for $TERM and no -T specified"
  TERM: dumb
jobs:
  test:
    name: Test with ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: run tests
        run: make test
      - name: Send coverage
        run: goveralls -coverprofile=gover.coverprofile -service=github
        env:
          # As per https://github.com/mattn/goveralls#github-actions
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Build docs and Coveralls integration
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Create .coverprofile for each targeted directory by re:running tests
        run: make test
      - name: Collect all .coverprofile files and save it to one file gover.coverprofile
        run: gover

      - run: ./script/sync-docs.sh
        if: ${{ github.ref == 'refs/heads/master' }}
